akwaibom = {
    'good': 'afon',
    'food': 'ndidia',
    'water': 'mmong',
    'family': 'mbonomi',
    'school': 'ufokngwet',
    'baby': 'eyen',
    'house': 'ufok',
    'god': ' abasi',
    'king': 'ubong',
    'father': 'ete',
    'mother': 'eka',
    'time': 'uduak',
    'lion': 'ekpe',
    'plate': 'usan',
    'spoon': ' ekpaan',
    'you': 'afu',
    'sitdown': 'tie',
    'come': 'di',
    'thankyou': 'sosong',
}
